from pydantic import BaseModel
from typing import Union, List

class InputRequestNSLKDD(BaseModel):
    duration: Union[int, float] = None
    protocol_type: Union[int, float] = None
    service: int = None
    flag: int  = None
    src_bytes: int = None
    dst_bytes: int = None
    wrong_fragment: int = None
    hot: int = None
    logged_in: int = None
    num_compromised: int = None
    count: int = None
    srv_count: int = None
    serror_rate: Union[int, float]
    srv_serror_rate: Union[int, float]
    rerror_rate: Union[int, float]

class SelectedFeaturetCICIDS2017(BaseModel):
    psh_flag_cnt: Union[str, int, float]
    fwd_seg_size_min: Union[str, int, float]
    flow_iat_max: Union[str, int, float]
    flow_iat_min: Union[str, int, float]
    ack_flag_cnt: Union[str, int, float]
    dst_port: Union[str, int, float]
    bwd_pkt_len_mean: Union[str, int, float]
    bwd_pkt_len_max: Union[str, int, float]
    bwd_pkt_len_min: Union[str, int, float]
    init_fwd_win_byts: Union[str, int, float]
    fwd_iat_max: Union[str, int, float]
    idle_mean: Union[str, int, float]
    idle_max: Union[str, int, float]
    bwd_seg_size_avg: Union[str, int, float]
    bwd_pkt_len_std: Union[str, int, float]
    bwd_iat_mean: Union[str, int, float]
    fwd_iat_std: Union[str, int, float]
    down_up_ratio: Union[str, int, float]
    pkt_len_max: Union[str, int, float]
    pkt_size_avg: Union[str, int, float]
    pkt_len_min: Union[str, int, float]
    pkt_len_std: Union[str, int, float]
    fwd_pkts_s: Union[str, int, float]
    pkt_len_mean: Union[str, int, float]
    flow_iat_std: Union[str, int, float]
    urg_flag_cnt: Union[str, int, float]
    fin_flag_cnt: Union[str, int, float]
    fwd_pkt_len_min: Union[str, int, float]
    subflow_fwd_pkts: Union[str, int, float]
    bwd_iat_max: Union[str, int, float]
    pkt_len_var: Union[str, int, float]
    fwd_iat_mean: Union[str, int, float]
    flow_duration: Union[str, int, float]
    fwd_iat_tot: Union[str, int, float]
    bwd_iat_std: Union[str, int, float]
    flow_iat_mean: Union[str, int, float]

class InputRequestCICIDS2017(BaseModel):
    src_ip: Union[str, int, float]
    dst_ip: Union[str, int, float]
    src_port: Union[str, int, float]
    dst_port: Union[str, int, float]
    protocol: Union[str, int, float]
    timestamp: Union[str, int, float]
    flow_duration: Union[str, int, float]
    flow_byts_s: Union[str, int, float]
    flow_pkts_s: Union[str, int, float]
    fwd_pkts_s: Union[str, int, float]
    bwd_pkts_s: Union[str, int, float]
    tot_fwd_pkts: Union[str, int, float]
    tot_bwd_pkts: Union[str, int, float]
    totlen_fwd_pkts: Union[str, int, float]
    totlen_bwd_pkts: Union[str, int, float]
    fwd_pkt_len_max: Union[str, int, float]
    fwd_pkt_len_min: Union[str, int, float]
    fwd_pkt_len_mean: Union[str, int, float]
    fwd_pkt_len_std: Union[str, int, float]
    bwd_pkt_len_max: Union[str, int, float]
    bwd_pkt_len_min: Union[str, int, float]
    bwd_pkt_len_mean: Union[str, int, float]
    bwd_pkt_len_std: Union[str, int, float]
    pkt_len_max: Union[str, int, float]
    pkt_len_min: Union[str, int, float]
    pkt_len_mean: Union[str, int, float]
    pkt_len_std: Union[str, int, float]
    pkt_len_var: Union[str, int, float]
    fwd_header_len: Union[str, int, float]
    bwd_header_len: Union[str, int, float]
    fwd_seg_size_min: Union[str, int, float]
    fwd_act_data_pkts: Union[str, int, float]
    flow_iat_mean: Union[str, int, float]
    flow_iat_max: Union[str, int, float]
    flow_iat_min: Union[str, int, float]
    flow_iat_std: Union[str, int, float]
    fwd_iat_tot: Union[str, int, float]
    fwd_iat_max: Union[str, int, float]
    fwd_iat_min: Union[str, int, float]
    fwd_iat_mean: Union[str, int, float]
    fwd_iat_std: Union[str, int, float]
    bwd_iat_tot: Union[str, int, float]
    bwd_iat_max: Union[str, int, float]
    bwd_iat_min: Union[str, int, float]
    bwd_iat_mean: Union[str, int, float]
    bwd_iat_std: Union[str, int, float]
    fwd_psh_flags: Union[str, int, float]
    bwd_psh_flags: Union[str, int, float]
    fwd_urg_flags: Union[str, int, float]
    bwd_urg_flags: Union[str, int, float]
    fin_flag_cnt: Union[str, int, float]
    syn_flag_cnt: Union[str, int, float]
    rst_flag_cnt: Union[str, int, float]
    psh_flag_cnt: Union[str, int, float]
    ack_flag_cnt: Union[str, int, float]
    urg_flag_cnt: Union[str, int, float]
    ece_flag_cnt: Union[str, int, float]
    down_up_ratio: Union[str, int, float]
    pkt_size_avg: Union[str, int, float]
    init_fwd_win_byts: Union[str, int, float]
    init_bwd_win_byts: Union[str, int, float]
    active_max: Union[str, int, float]
    active_min: Union[str, int, float]
    active_mean: Union[str, int, float]
    active_std: Union[str, int, float]
    idle_max: Union[str, int, float]
    idle_min: Union[str, int, float]
    idle_mean: Union[str, int, float]
    idle_std: Union[str, int, float]
    fwd_byts_b_avg: Union[str, int, float]
    fwd_pkts_b_avg: Union[str, int, float]
    bwd_byts_b_avg: Union[str, int, float]
    bwd_pkts_b_avg: Union[str, int, float]
    fwd_blk_rate_avg: Union[str, int, float]
    bwd_blk_rate_avg: Union[str, int, float]
    fwd_seg_size_avg: Union[str, int, float]
    bwd_seg_size_avg: Union[str, int, float]
    cwe_flag_count: Union[str, int, float]
    subflow_fwd_pkts: Union[str, int, float]
    subflow_bwd_pkts: Union[str, int, float]
    subflow_fwd_byts: Union[str, int, float]
    subflow_bwd_byts: Union[str, int, float]

class Response(BaseModel):
    status_code: int = 200
    result: str = "normal"
    confidence: Union[float, int, dict, str] = None


